name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir-version: [1.9.4]
        otp-version: [22.2]

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    # Cache Mix Dependencies based on runner, elixir and otp versions and mix.lock
    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v1
      id: mix-cache #id to use in retrieve action
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    # Install mix deps if cache not hit
    - name: Install Mix Dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    # Cache the _build folder
    - name: Retrieve Build Cache
      uses: actions/cache@v1
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    # Compile mix dependencies if the _build folder was not cached
    - name: Compile Mix Dependencies
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: MIX_ENV=test mix deps.compile

    - name: Run Tests
      run: mix test

    # Cache dialyzer outputs
    - name: Retrieve PLT Cache
      uses: actions/cache@v1
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Create PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        MIX_ENV=test mix dialyzer --plt

    # Run Dialyzer
    - name: Run dialyzer
      run: MIX_ENV=test mix dialyzer --no-check
